import { z } from 'zod';
import { structuredCall } from './llm';
import { SHARED_PRINCIPLES } from './elicitation.chain';
import { LibraryQuestion } from '../models/question-library';
import { Channel } from '../types';

// Personality engine (docs/personality-analysis-engine-spec.md §3, tracked in
// docs/personality-engine-implementation-plan.md Iteration 3). A sibling to elicitation.chain.ts
// rather than a mode on it (decision recorded here per the plan's "decide and record which"):
// elicitation.chain.ts is step-shaped (one completionCriteria string, one fixed step name) and
// drives logistics unchanged; this chain is topic-shaped (one question, its own close criteria,
// optional per-question probe rules) and drives deep_prompts exclusively via
// topic-conversation.service.ts. Sharing SHARED_PRINCIPLES keeps the "never ask the candidate to
// rate themselves" framing identical between the two without folding topic-thread concepts
// (question objects, close criteria, probe tables) into elicitation.chain.ts's simpler shape.

const turnSchema = z.object({
  reply: z
    .string()
    .describe(
      'Your next message to the candidate: one focused follow-up question, or (only when ' +
        'closeTopic is true) a brief, warm line acknowledging the topic is done — never both.'
    ),
  closeTopic: z
    .boolean()
    .describe('True once the CLOSE THIS TOPIC criteria below are met, or the candidate signaled they are done with this topic.'),
  closedBy: z
    .enum(['model', 'user'])
    .describe(
      '"user" only when the candidate explicitly said something like "that\'s all I\'ve got on ' +
        'that" — otherwise "model". Ignored when closeTopic is false.'
    )
});

export interface TopicTurnParams {
  question: LibraryQuestion;
  channel: Channel;
  /** Full exchange history for this topic thread, oldest first — always starts with the opening
   *  assistant exchange (the question's own prompt text, inserted directly by
   *  topic-conversation.service.ts, not generated by this chain) and has at least one user reply
   *  by the time this is called. */
  history: Array<{ role: 'user' | 'assistant'; content: string }>;
}

export interface TopicTurnResult {
  reply: string;
  closeTopic: boolean;
  closedBy: 'model' | 'user';
}

// Verbatim from spec §3 "Topic completion", with the user-initiated close folded in as one more
// bullet (the spec lists it as always-available and separately-honored, but there's no separate
// intent-parsing step here — the model reading it as one more close condition is simpler and the
// prompt already tells it to honor it immediately and never penalize it).
const CLOSE_CRITERIA_BLOCK = [
  'CLOSE THIS TOPIC WHEN ANY OF THE FOLLOWING HOLD:',
  '- The primary dimension(s) for this question have at least two pieces of evidence at moderate',
  '  strength or better, and the last exchange added none.',
  '- The person has given at least one concrete, situated incident (a specific time, place, and',
  '  outcome) rather than only general self-description.',
  '- Two consecutive exchanges have restated earlier material without new specifics.',
  '- The person signals fatigue, reluctance, or discomfort with the topic — close immediately and',
  '  do not return to it.',
  '- The person explicitly says they\'re done with this topic (e.g. "that\'s all I\'ve got on',
  '  that") — always honor this immediately, it is never penalized. Set closedBy to "user".',
  '',
  'OTHERWISE, ask one follow-up that goes after what is missing: the incident if they gave',
  'generalities, the outcome if they gave setup, their own role if they described only others.',
  '',
  'Never ask a follow-up whose only purpose is to confirm something already said.'
].join('\n');

function dimensionLine(question: LibraryQuestion): string {
  const entries = Object.entries(question.dimensionLoads);
  const primary = entries.filter(([, load]) => load === 'P').map(([dim]) => dim);
  const secondary = entries.filter(([, load]) => load === 's').map(([dim]) => dim);
  return (
    `Primary dimension(s) for this question: ${primary.join(', ') || 'none'}.` +
    (secondary.length ? ` Secondary: ${secondary.join(', ')}.` : '')
  );
}

function probeBlock(question: LibraryQuestion): string {
  if (!question.probeRules?.length) return '';
  const rows = question.probeRules
    .map((r) => `- If ${r.trigger.toLowerCase()} → ask: "${r.probe}" (targets: ${r.targets})`)
    .join('\n');
  return (
    'ADAPTIVE PROBES — if the candidate\'s last answer matches one of these triggers, prefer the ' +
    'matching probe as your one follow-up (still just one question, and still subject to the ' +
    `close criteria above):\n${rows}`
  );
}

/**
 * Drives one turn of an open topic thread (spec §3). Unlike runElicitationTurn, this never
 * generates the opening question — topic-conversation.service.ts inserts the library's own
 * prompt text verbatim for that — so `history` always has at least one exchange already.
 */
export async function runTopicTurn(params: TopicTurnParams): Promise<TopicTurnResult> {
  const { question, channel, history } = params;

  const system = [
    SHARED_PRINCIPLES,
    channel === 'email'
      ? 'This is an email thread — a topic can reasonably take four or five exchanges over a ' +
        'week. Do not rush to close; each new exchange should go somewhere a single live-chat ' +
        'follow-up would not have had time to reach. The constraint is whether the last exchange ' +
        'added new evidence, not a fixed count.'
      : 'This is live chat — usually one follow-up is right; more starts to read as ' +
        'interrogation. Close as soon as the criteria below are met.',
    `Topic question: "${question.prompt}"`,
    dimensionLine(question),
    CLOSE_CRITERIA_BLOCK,
    probeBlock(question)
  ]
    .filter(Boolean)
    .join('\n\n');

  const human = history.map((m) => `${m.role === 'user' ? 'Candidate' : 'You'}: ${m.content}`).join('\n');

  const result = await structuredCall(turnSchema, system, human, 0.5);

  return { reply: result.reply, closeTopic: result.closeTopic, closedBy: result.closedBy };
}
